### ISSUE TITLE
Релиз

### ISSUE THREAD

**Issue by TFK70** [atls/figma#17]
### Info

Здесь будут собраны все тикеты которые нужно закрыть до релиза и обсуждение ключевых моментов

### Список Задач

- [x] https://github.com/atls/figma/issues/18

**Comment by TFK70** [comment]
@carminio можешь сформулировать статус генераторов после твоих фичей? Чего не хватает до конечного использования/узкие места и т.п.

Пока напиши сюда комментом, обсудим, и составим задачи

**Comment by carminio** [comment]
@TFK70 В генераторе colors не хватает [этого](https://github.com/torin-asakura/shdvor/blob/master/ui/theme/src/theme/colors.ts#L16) в остальном вроде всё конечный результат

**Comment by TFK70** [comment]
> @TFK70 В генераторе colors не хватает [этого](https://github.com/torin-asakura/shdvor/blob/master/ui/theme/src/theme/colors.ts#L16) в остальном вроде всё конечный результат

Не понял немного, распиши подробнее чего не хватает

**Comment by carminio** [comment]
> > @TFK70 В генераторе colors не хватает [этого](https://github.com/torin-asakura/shdvor/blob/master/ui/theme/src/theme/colors.ts#L16) в остальном вроде всё конечный результат
> 
> Не понял немного, распиши подробнее чего не хватает

Генератор colors генерит сейчас в таком виде:

```js
const colors = {
  white: 'rgba...',
  black: 'rgba...',
  .....
}
```

А не в таком:

```js
const colors = {
  white: 'rgba...',
  black: 'rgba...',
  button: {
    primary: {
      default: {
        background: 'rgba(224, 29, 81, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(224, 29, 81, 1)',
      },
      hover: {
        background: 'rgba(200, 21, 70, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(200, 21, 70, 1)',
      },
      pressed: {
        background: 'rgba(177, 16, 52, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(177, 16, 52, 1)',
      },
      disabled: {
        background: 'rgba(10, 10, 11, 0.04)',
        font: 'rgba(172, 173, 183, 1)',
        border: 'rgba(10, 10, 11, 0.04)',
      },
    },
},
  input: {
    primary: {
      default: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        fontColor: 'rgba(10, 10, 11, 1)',
      },
      hover: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      pressed: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      focus: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      disabled: {
        background: 'rgba(247, 247, 247, 1)',
        border: 'rgba(247, 247, 247, 1)',
        font: 'rgba(195, 195, 195, 1)',
        label: 'rgba(128, 128, 128, 1)',
      },
      error: 'rgba(213, 52, 52, 1)',
    },
  },
  .....
```

В общем состояния для кнопок, инпутов нужно руками вписывать

**Comment by TFK70** [comment]
@carminio понял, составь тогда задачу на это

**Comment by TorinAsakura** [comment]
@carminio полагаю, мы можем расширить нашего walker'a для доступа ко внутренним слоям ноды?

**Comment by TorinAsakura** [comment]
Closed by https://github.com/atls/figma/pull/20
