### ISSUE TITLE
Advanced color generator

### ISSUE THREAD

**Issue by carminio** [atls/figma#18]
### Задача

Усовершенствовать генератор colors. Добавить цвета для состояний кнопок, инпутов

### Info

Сейчас генерится так:

```js
const colors = {
  white: 'rgba...',
  black: 'rgba...',
  .....
}
```

Нужно сделать так:

```js
const colors = {
  white: 'rgba...',
  black: 'rgba...',
  button: {
    primary: {
      default: {
        background: 'rgba(224, 29, 81, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(224, 29, 81, 1)',
      },
      hover: {
        background: 'rgba(200, 21, 70, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(200, 21, 70, 1)',
      },
      pressed: {
        background: 'rgba(177, 16, 52, 1)',
        font: 'rgba(255, 255, 255, 1)',
        border: 'rgba(177, 16, 52, 1)',
      },
      disabled: {
        background: 'rgba(10, 10, 11, 0.04)',
        font: 'rgba(172, 173, 183, 1)',
        border: 'rgba(10, 10, 11, 0.04)',
      },
    },
},
  input: {
    primary: {
      default: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        fontColor: 'rgba(10, 10, 11, 1)',
      },
      hover: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      pressed: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      focus: {
        background: 'rgba(10, 10, 11, 0.04)',
        border: 'transparent',
        font: 'rgba(10, 10, 11, 1)',
      },
      disabled: {
        background: 'rgba(247, 247, 247, 1)',
        border: 'rgba(247, 247, 247, 1)',
        font: 'rgba(195, 195, 195, 1)',
        label: 'rgba(128, 128, 128, 1)',
      },
      error: 'rgba(213, 52, 52, 1)',
    },
  },
  .....
```

**Comment by carminio** [comment]
@TFK70 Чтобы найти кнопки в фигме, необходимо привязываться к названию [главного фрейма](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=1267%3A38045&t=aT1JlRuM82i72EsA-4), это название будет служить в качестве ID, с помощью которого получаем все кнопки находящиеся внутри него. Отсюда нужна синхронизация с дизайнерами, чтобы [фрейм](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=1267%3A38045&t=aT1JlRuM82i72EsA-4) с кнопками всегда имел одно и тоже название на всех проектах

**Comment by TFK70** [comment]
> @TFK70 Чтобы найти кнопки в фигме, необходимо привязываться к названию [главного фрейма](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=1267%3A38045&t=aT1JlRuM82i72EsA-4), это название будет служить в качестве ID, с помощью которого получаем все кнопки находящиеся внутри него. Отсюда нужна синхронизация с дизайнерами, чтобы [фрейм](https://www.figma.com/file/pUWwcuHo61RiwLEzNztoGZ/Kinoreporter-%7C-Web-site?node-id=1267%3A38045&t=aT1JlRuM82i72EsA-4) с кнопками всегда имел одно и тоже название на всех проектах

Надо зафиксировать этот и все подобные моменты  в README проекта, чтобы было что-то наподобие конвенции, которую мы передадим дизайнерам и к которой они в будущем смогут обращаться
