### ISSUE TITLE
Обновление зависимостей `figma-file-loader` и `figma-utils`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/figma#23]
## С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

## Что предстоит сделать?

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

## Пример реализации

  https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
  `yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by Nelfimov** [comment]
Закрыто: https://github.com/atls/figma/pull/26

**Comment by Nelfimov** [comment]
Закрыто: https://github.com/atls/figma/pull/26
