### ISSUE TITLE
Обновление зависимостей `figma-theme` генераторов

### ISSUE THREAD

**Issue by SlumberyDude** [atls/figma#24]
## С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях модулей:
- [x] `@atls/figma-theme-colors-generator`
- [x] `@atls/figma-theme-generator-common`
- [x] `@atls/figma-theme-line-heights-generator`
- [x] `@atls/figma-theme-radii-generator`
- [x] `@atls/figma-theme-shadows-generator`

## Что предстоит сделать?

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

## Пример реализации

  https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
  `yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by Nelfimov** [comment]
Закрыто: https://github.com/atls/figma/pull/26
