### ISSUE TITLE
Обновление зависимостей `figma-theme-font-*`, `figma-theme` 

### ISSUE THREAD

**Issue by SlumberyDude** [atls/figma#25]
## С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях для модулей:
- [x] `@atls/figma-theme-font-sizes-generator`
- [x] `@atls/figma-theme-font-weights-generator`
- [x] `@atls/theme-fonts-generator`
- [x] `@atls/figma-theme-cli`
- [x] `@atls/figma-theme`

## Что предстоит сделать?

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

## Пример реализации

  https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
  `yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by Nelfimov** [comment]
Закрыто: https://github.com/atls/figma/pull/26
