### ISSUE TITLE
Theme generator

### ISSUE THREAD

**Issue by TFK70** [atls/figma#3]
### Задача

- [x] Перевести https://github.com/atls/figma/pull/2 на актуальный стек, тулзы
- [x] Протестировать функционал. Если что-то не будет работать и не будет возможности оперативно это пофиксить - нужно составить месседж со всей инфой о проблеме

**Comment by brusselboy** [comment]
## Итог
@TFK70 

С генерацией fontSizes разобрался, один момент выявил который можно поправить, если значений больше чем [констант](https://github.com/atls/figma/blob/feat/theme/theme/theme-font-sizes-generator/src/Constants.ts), то они не записываются в конечный файл, вижу решение - это расширить список констант.

### Сгенерированный fontSizes.ts

С нынешним списком констант:

<details>

```js
export const fontSizes = {
  atomic: 12,
  micro: 13,
  tiny: 14,
  small: 15,
  normal: 16,
  regular: 18,
  extra: 20,
  medium: 24,
  increased: 28,
  large: 31,
  huge: 32,
  giant: 36,
  undefined: 128,
};
```

</details>

### Пример с расширенным списком

<details>

```js
export const fontSizes = {
  atomic: 12,
  micro: 13,
  tiny: 14,
  small: 15,
  normal: 16,
  regular: 18,
  extra: 20,
  semiExtra: 24,
  semiRegular: 28,
  medium: 31,
  increased: 32,
  L: 36,
  XL: 40,
  XXL: 44,
  XXXL: 48,
  XXXXL: 60,
  large: 64,
  big: 72,
  huge: 74,
  giant: 80,
  ulta: 84,
  giga: 94,
  penta: 103,
  ligma: 128,
};

```

</details>

Нужно только определиться с неймингом констант
